@PriceNegotiationApp_HostAddress = http://localhost:5011

GET {{PriceNegotiationApp_HostAddress}}/api/product
Accept: application/json

###
GET {{PriceNegotiationApp_HostAddress}}/api/product/3

###

POST {{PriceNegotiationApp_HostAddress}}/api/product
Content-Type: application/json

{
  "Name": "Rollerblades",
  "Price":45.45
}